### ISSUE TITLE
Add more docs

### ISSUE THREAD

**Issue by loliconshik3** [Big-Onche/Cube-Conflict#12]
We absolutely need docs for understanding, how to balance heroes, add new heroes and weapons, etc...

**Comment by Big-Onche** [comment]
Explaining how to add weapons or classes might be difficult because we must dive big into programming.
However, I agree that the game needs documentation about classes, objects, weapons, etc.
That's why I opened a wiki (wiki.cube-conflict.com). Like the main website, it's going to need an English version.
